### ISSUE TITLE
Add Dynamic Texture Editor Feature

### ISSUE THREAD

**Issue by henyana** [raananw/BabylonJS-Material-Editor#2]
Hi Raanan,

This Material Editor was great! 
Add Dynamic Texture Feature Editor it would be nice +1

Regards,
Hendra

**Comment by RaananW** [comment]
Hi, thanks for the suggestion :smile:
I'm planning a complete new version of the editor, that will be hopefully ready till 2.3 is out (but who knows...). 
This version will include dynamic textures with text, procedural textures and hopefully parts of the material library.

**Comment by henyana** [comment]
Great! Can't wait to play  :+1:
